### ISSUE TITLE
Optionally get image src from frontmatter

### ISSUE THREAD

**Issue by tokenshift** [tokenshift/obsidian-page-gallery#21]
Allow users to specify what image to use in the frontmatter for a particular page, rather than parsing the page contents for the first image in it. Example:

```yaml
---
pageGallery:
  src: some_image.jpg
---
```
