### ISSUE TITLE
Add a radius option

### ISSUE THREAD

**Issue by stevenlis** [tokenshift/obsidian-page-gallery#27]
Could you please consider adding a radius option so that the users could modify those corners? 
![CS-Yxbax9yF@2x](https://user-images.githubusercontent.com/33796896/221080434-b0e3e450-1217-4e73-ad19-a00ab61c4643.png)

**Comment by Bluemoondragon07** [comment]
@StevenLi-DS,  if you're interested, there is a current way to change the border radius manually with a snippet.
```css
.page-gallery__tile {
border-radius: /* type custom value here */;
}
```
