### ISSUE TITLE
Text format and text wrapping for image titles

### ISSUE THREAD

**Issue by groepl** [tokenshift/obsidian-page-gallery#69]
<img width="574" alt="image" src="https://github.com/tokenshift/obsidian-page-gallery/assets/114583103/b934777e-75fd-4c07-9bc1-e814ba415d1d">

It would be nice to be able to format the titles (file.name) below the images. No bold, no shadow, text normal or small, wrap text over different lines (not cut by ...).

Thank you for your amazing plugin. It's fun to use it. :-)

**Comment by tokenshift** [comment]
You can customize page-gallery styling by using [CSS snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets). Example for removing/overriding the default style for "filename as the first/top displayed field":

```css
.page-gallery__field[data-page-gallery-field-expression="file.name"]:first-child {
  font-weight: normal;
  text-shadow: none;
  white-space: normal;
}
```

I'll leave this ticket open as I think it makes sense to add an option for whether the filename field should be highlighted as is the default right now; but any more advanced or custom styling will still need CSS snippets rather than being built-in.
