### ISSUE TITLE
Filter tags without its subtags

### ISSUE THREAD

**Issue by 3esmit** [tokenshift/obsidian-page-gallery#74]
This is an example of my tag structure:

- #page
- #page/project
- #page/project/proj1
- #page/project/proj2
- #page/research
- #page/research/res1
- #page/research/res2
- #page/notes

I want to have a page gallery that display just pages that have the tag #page, but not the pages that have a subtag of #page, such as #page/project or #page/project/proj1.

How do I do that in the from source?

**Comment by 3esmit** [comment]
This is a way I manage to do it:
````
```page-gallery
fields: [file.name]
columns: 3
filter: false
orientation: landscape
views:
  - name: Pages
    from: '#page' 
    where: contains(file.tags, "#page") and !any(contains(file.tags, "#page/"))
```
````
